13 tokyo
alarm-redist/japan pull request #40
Opened 2022-04-30 21:34 UTC by kentoyamada100

2022-05-01 16:46 UTC, shomiyazaki requested changes
@kentoyamada100 I have made some minor changes in 01 and 02.
Also, please check my suggestions in this comments.

Then, please delete `index_files/` , and knit MD and RM!

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/03_visualization_13_tokyo.R
> +functioning_results_special_wards <- filter(results_special_wards, multi == 0)
**One suggestion**

How about filtering out plans with more splits team status quo?

sq_mun_splits_special_wards <- 14

functioning_results_special_wards <- filter(results_special_wards,
mun_splits <=  sq_mun_splits_special_wards,
 multi == 0)

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/03_visualization_13_tokyo.R
> +  filter(respect_gun == length(respect_gun_code), multi == 0)
Same suggestion with 23ku

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/13_tokyo_hr_2020_doc.md
> +* 臨海部を中心に、以下の地域を隣接するものとして扱った。
I think we need to add some more rationale here.
And I think we should not use 中心に here.

How about
臨海部を現行の区割りに従い、橋で結ばれている臨海部の以下の地域は、隣接しているものとして扱った。
If this is true and applicable?

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/13_tokyo_hr_2020_doc.md
> +* 市区町村を分割すること、及び市区町村を複数の選挙区に分割することを抑制すべく、制約を設定
市区町村の分割数の制限 (`add_constr_splits `) と、市区町村の複数選挙区への分割の制限(`add_constr_multisplits `) をそれぞれを設定

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/13_tokyo_hr_2020_doc.md
> +* 各選挙区の人口 :
We need to write that our base unit is 小地域

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/13_tokyo_hr_2020_doc.md
> +<!---[When manual processing was necessary when assessing contiguity] 宮城野区港５丁目を飛び地として扱わないため、作成した区割り案に飛び地が生じているかどうか判断する際、一時的に宮城野区港５丁目及び隣接する七ヶ浜町をデータから除外した。-->
I think we cam remove this line

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/index.Rmd
> +ggplot() +
I understand why you do not include red point reference of city name.

However, it will be more visually appealing and user friendly if we add 3~4 wards name here.
And I assume Prof. Imai will ask about this in our next meeting.

Then, our question would be
Which ward should we pick up?

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/index.Rmd
> +# 共起分析
To clarify just in case

Can we interpret co-occurance for the urbans as same as the rurals?

2022-05-01 16:46 UTC, shomiyazaki commented on analyses/13_tokyo/index.Rmd
> +  + 多摩地域: 9
Please reflect changes from the readme markdown file.

2022-05-02 01:22 UTC, kentoyamada100 commented on analyses/13_tokyo/01_prep_13_tokyo.R
> +pref_geom_only$mun_code <- substr(pref_geom_only$code, start = 1, stop = 5)
We need to keep it as it is. 5 corresponds to the fact that the length of municipality codes is 5

2022-05-02 01:29 UTC, kentoyamada100 commented on analyses/13_tokyo/03_visualization_13_tokyo.R
> +functioning_results_special_wards <- filter(results_special_wards, multi == 0)
That works for Tokyo, where there is only one 郡, but not in general. We want to make sure that we are not splitting the 郡 that are not split under the status quo. If we only limit the number of 郡 splits, that does not guarantee that we are keeping together the 郡 that is respected under the enacted plan

I coded this part specifically so that this post-processing step works in general, so I would appreciate it if you could keep this as it is.

2022-05-02 01:44 UTC, kentoyamada100 commented on analyses/13_tokyo/index.Rmd
> +# 共起分析
The basic logic is the same. However, one thing to keep in mind is that the colors do not necessarily correspond to districts; rather, they correspond to clusters of 小地域 that tend to be in the same district as its adjacent 小地域. Let's discuss this when we meet tomorrow

2022-05-02 01:50 UTC, kentoyamada100 commented on analyses/13_tokyo/index.Rmd
> +ggplot() +
Another thing we might keep in mind is that the plot might become harder to interpret if we plot cities in ２３区. Since the basic unit is 小地域 and the boundaries tend to be quite complex in ２３区, plotting the cities might add to that complexity...

2022-05-02 04:48 UTC, shomiyazaki approved these changes

2022-05-02 04:48 UTC, merged