23 aichi
alarm-redist/japan pull request #42
Opened 2022-05-24 12:43 UTC by kentoyamada100

2022-05-29 07:45 UTC, shomiyazaki reviewed
Hi Kento! Thanks for your PR! 
Codes in 01 and 02, README looks fine. I have made a few comments, please check them. 
I will continue checking on HTML output and coocuuracne.
Thanks

2022-05-29 07:45 UTC, shomiyazaki commented on analyses/23_aichi/02_sim_23_aichi.R
> +hist(plans_diversity(sim_smc_pref))
While it might not be so important, I will comment on this just in case. Although the code looks fine, the planned diversity seems to be very sensitive to randomness. 
The first photo is what your saved data looks like, the second is my VM (set.seed = 12345) and the third is my VM (
![Screen Shot 2022-05-29 at 16 27 02](https://user-images.githubusercontent.com/70427938/170857508-f32466fe-1c8e-4b8b-b67c-cf59e4de4601.png)
set.seed = 123).
![Screen Shot 2022-05-29 at 14 53 27](https://user-images.githubusercontent.com/70427938/170857514-3be61e6d-5a14-4ecd-8977-6be9f42ddb77.png)
![Screen Shot 2022-05-29 at 16 24 59](https://user-images.githubusercontent.com/70427938/170857515-0adb35b1-d10f-4a03-bcc3-0bbebf9f6c9d.png)

2022-05-29 07:45 UTC, shomiyazaki commented on analyses/23_aichi/03_visualization_23_aichi.R
> +mun_split <- redist::redist.splits(pref_smc_plans, pref_map$code)
Is your `redist` updated? I get this error in Saitama too because the output of this code is a matrix. Also, the reference page says its output is matrix too. https://alarm-redist.github.io/redist/reference/redist.splits.html
![Screen Shot 2022-05-29 at 16 38 56](https://user-images.githubusercontent.com/70427938/170857576-2e3c881e-f2cb-4c5a-b691-75c550c1d382.png)

2022-05-29 11:45 UTC, kosukeimai commented on analyses/23_aichi/03_visualization_23_aichi.R
> +mun_split <- redist::redist.splits(pref_smc_plans, pref_map$code)
@shomiyazaki Try increasing the number of samples until this becomes more stable

2022-05-30 02:41 UTC, shomiyazaki commented on analyses/23_aichi/03_visualization_23_aichi.R
> +mun_split <- redist::redist.splits(pref_smc_plans, pref_map$code)
Thank you. We will retry with the new SMC, and increase the number of samples.

2022-05-30 02:50 UTC, shomiyazaki requested changes
Hi @kentoyamada100 ! The index.rmd and README documents look great, and I made a comments on the graphics. I will review again after the new SMC

2022-05-30 02:50 UTC, shomiyazaki commented on analyses/23_aichi/index.Rmd
> +              color = c("white", "black", "black", "white", "black"),
I think 名古屋 should be black in this appearance

2022-05-30 02:50 UTC, shomiyazaki commented on analyses/23_aichi/index.Rmd
> +              color = c("white", "black", "white", "black", "black"),
I think 名古屋 should be in black, and move left

2022-06-19 08:28 UTC, closed without merging