11 saitama
alarm-redist/japan pull request #47
Opened 2022-06-03 15:30 UTC by shomiyazaki

@kentoyamada100 
Hi! The analysis for Saitama has been completed, and it would be appreciated if you start reviewing them. 
The documentation on README and index.rmd will be completed this weekend. Please start reviewing them from the 01-03 coding part, as well as the plot output (labels are subjected to change).
The following lines are the output of `summary(sim_smc_pref)`. I run the simulation with various constraints and n_sim to remove the warning (Chiba is in that process now). 
Thank you in advance, and I am looking forward to getting feedback from you. 

> summary(sim_smc_pref)
SMC: 150,000 sampled plans of 16 districts on
2,851 units
`adapt_k_thresh`=0.985 • `seq_alpha`=0.5
`est_label_mult`=1 • `pop_temper`=0.05

Plan diversity 80% range: 0.029 to 0.741

Sampling diagnostics for SMC run 1 of 2
         Eff. samples (%) Acc. rate Log wgt. sd
Split 1    71,132 (94.8%)     49.7%        0.43
Split 2    61,745 (82.3%)     68.1%        0.48
Split 3    53,962 (71.9%)     78.0%        0.56
Split 4    46,490 (62.0%)     91.8%        0.63
Split 5    39,401 (52.5%)     97.0%        0.71
Split 6    32,626 (43.5%)     99.1%        0.78
Split 7    26,006 (34.7%)     96.6%        0.84
Split 8    19,907 (26.5%)     94.3%        0.93
Split 9    14,351 (19.1%)     97.3%        1.04
Split 10    9,711 (12.9%)     98.3%        1.15
Split 11     5,498 (7.3%)     98.5%        1.29
Split 12     2,365 (3.2%)     97.5%        1.44
Split 13       869 (1.2%)     87.8%        1.68
Split 14       365 (0.5%)     63.7%        2.16
Split 15       641 (0.9%)     42.1%        1.91
Resample       168 (0.2%)       NA%        8.82
           Max. unique Est. k    
Split 1  47,270 (100%)     99    
Split 2  46,565 ( 98%)     66    
Split 3  44,047 ( 93%)     51    
Split 4  41,388 ( 87%)     32    
Split 5  38,303 ( 81%)     20    
Split 6  35,196 ( 74%)     11    
Split 7  31,405 ( 66%)     16    
Split 8  27,438 ( 58%)     17    
Split 9  23,320 ( 49%)     10    
Split 10 19,348 ( 41%)      6    
Split 11 16,054 ( 34%)      4    
Split 12 13,193 ( 28%)      3  * 
Split 13 10,524 ( 22%)      3  * 
Split 14  8,286 ( 17%)      3  * 
Split 15  8,354 ( 18%)      3  * 
Resample  1,381 (  3%)     NA  * 

Sampling diagnostics for SMC run 2 of 2
         Eff. samples (%) Acc. rate Log wgt. sd
Split 1    71,149 (94.9%)     41.8%        0.43
Split 2    61,723 (82.3%)     73.4%        0.48
Split 3    53,901 (71.9%)     81.0%        0.55
Split 4    46,408 (61.9%)     86.9%        0.63
Split 5    39,100 (52.1%)     95.6%        0.70
Split 6    32,136 (42.8%)     93.3%        0.78
Split 7    26,190 (34.9%)     97.9%        0.86
Split 8    19,865 (26.5%)     98.9%        0.94
Split 9    14,200 (18.9%)     99.1%        1.03
Split 10    9,020 (12.0%)     96.5%        1.15
Split 11     4,856 (6.5%)     90.6%        1.31
Split 12     2,437 (3.2%)     93.7%        1.50
Split 13       830 (1.1%)     88.8%        1.68
Split 14       209 (0.3%)     68.9%        2.21
Split 15     1,738 (2.3%)     40.0%        2.37
Resample        41 (0.1%)       NA%        7.80
           Max. unique Est. k    
Split 1  47,219 (100%)    117    
Split 2  46,569 ( 98%)     60    
Split 3  43,862 ( 93%)     48    
Split 4  41,292 ( 87%)     38    
Split 5  38,137 ( 80%)     23    
Split 6  34,934 ( 74%)     24    
Split 7  31,155 ( 66%)     13    
Split 8  27,729 ( 58%)      8    
Split 9  23,367 ( 49%)      5    
Split 10 19,343 ( 41%)      9    
Split 11 15,821 ( 33%)     14    
Split 12 13,395 ( 28%)      8  * 
Split 13 10,652 ( 22%)      5  * 
Split 14 10,226 ( 22%)      7  * 
Split 15  5,575 ( 12%)      5  * 
Resample  2,628 (  6%)     NA  * 

•  Watch out for low effective samples, very low
acceptance rates (less than 1%), large std.
devs. of the log weights (more than 3 or so),
and low numbers of unique plans. R-hat values
for summary statistics should be between 1 and
1.05.
• (*) Bottlenecks found: Consider weakening or
removing constraints, or increasing the
population tolerance. If the accpetance rate
drops quickly in the final splits, try
increasing `pop_temper` by 0.01. To visualize
what geographic areas may be causing problems,
try running the following code. Highlighted
areas are those that may be causing the
bottleneck.
    plot(<map object>, rowMeans(as.matrix(sim_smc_pref)) == <bottleneck iteration>)

2022-06-06 12:19 UTC, shomiyazaki commented
@kentoyamada100 Documentation and web output are ready now. Thank you in advance, and I am looking forward to your feedback and review!

2022-06-12 07:14 UTC, kentoyamada100 requested changes
I will re-do the review once you fix the 郡 codes, explain your methods, and use the new method to assign the population to the largest area in each pseudo-census block

2022-06-12 07:14 UTC, kentoyamada100 commented on analyses/11_saitama/01_prep_11_saitama.R
> +pref_mutual[pref_mutual$code == "114420110",]$pop <-
This meaning of this sentence is unclear. What do you mean?

2022-06-12 07:14 UTC, kentoyamada100 commented on analyses/11_saitama/02_sim_11_saitama.R
> +# set aside guns from pref_non_gun
<img width="342" alt="Screen Shot 2022-06-12 at 16 03 24" src="https://user-images.githubusercontent.com/84626919/173221589-704225c4-64a2-45c3-97ab-784da9ab7d36.png">
I'm not sure what you did here but the municipality codes and the 郡 codes do not match

2022-06-12 07:14 UTC, kentoyamada100 commented on analyses/11_saitama/02_sim_11_saitama.R
> +    code %in% c(11324) == TRUE ~ 11324,
<img width="681" alt="Screen Shot 2022-06-12 at 16 04 33" src="https://user-images.githubusercontent.com/84626919/173221625-a34cfcad-49c9-4e1d-ab7e-6b7afbedb6dd.png">
Also, what happened to this 郡?

2022-06-12 07:14 UTC, kentoyamada100 commented on analyses/11_saitama/02_sim_11_saitama.R
> +new_rows[1, ]$pop <- pref[1, ]$pop
I guess you need to use the new method (i.e. calculate the area of each census block)

2022-06-12 07:14 UTC, kentoyamada100 commented on analyses/11_saitama/02_sim_11_saitama.R
> +
<img width="704" alt="Screen Shot 2022-06-12 at 16 08 11" src="https://user-images.githubusercontent.com/84626919/173221724-aecb9a22-70cd-456e-b87d-ef5f558e4b43.png">
Did you try weakening the constraints?

2022-06-12 07:14 UTC, kentoyamada100 commented on analyses/11_saitama/03_visualization_11_saitama.R
> +# Code of 郡 that are split under the status quo
Please explain more clearly what you did here

2022-06-12 07:14 UTC, kentoyamada100 commented on analyses/11_saitama/03_visualization_11_saitama.R
> +gun_split <- gun_split[,1]
I'm not sure whether the 郡 splits were counted correctly since the 郡 codes were not assigned properly

2022-06-12 08:17 UTC, shomiyazaki commented on analyses/11_saitama/02_sim_11_saitama.R
> +# set aside guns from pref_non_gun
Thank you @kentoyamada100 for your review. Although I have tried in two VM, what you mentioned above did not happen. Would you try running every line before this code?

![Screen Shot 2022-06-12 at 17 14 55](https://user-images.githubusercontent.com/70427938/173223915-bbf57584-fd2d-4465-bfc9-a1d263d4d63f.png)
![Screen Shot 2022-06-12 at 17 15 03](https://user-images.githubusercontent.com/70427938/173223917-ce02fc3b-f472-4da0-9558-91b413ee4b45.png)

2022-06-12 08:25 UTC, shomiyazaki commented on analyses/11_saitama/02_sim_11_saitama.R
> +    code %in% c(11324) == TRUE ~ 11324,
This 北足立郡 (contains only 伊奈町 11301)  is merged into one unit.

2022-06-16 06:38 UTC, shomiyazaki commented
@kentoyamada100 Hi! I have reflected changes on your reviews, and re-run the simulation with `runs=4L`. 
Also, would you mind `knitting` this `index.rmd` on your computer? Somehow I could not delete the white lines on my Mac (I can do that in VM), while VM cannot compile Japanese fonts. Thank you in advance, and I am looking forward to your reviews and comments

2022-07-05 00:49 UTC, shomiyazaki commented on analyses/11_saitama/index.Rmd
> +* 隣接する地域と同じ選挙区に属する傾向が強い地域同士の集まりを、k = 35 設定
K = 30

@kentoyamada100 Would you knit this Rmd for me? My VM won’t compile Japanese, and I only have iPad at school. Thanks!

2022-07-05 07:21 UTC, kentoyamada100 requested changes
@shomiyazaki I only pointed out the most significant mistakes in my comments, and I corrected many other parts at my discretion to save you some time. In addition to making the changes I proposed, please review your codes once again to review the changes I made

After doing all that, please do the following:

- [x] Upload the data to Dataverse
- [ ] Publish the page

2022-07-05 07:21 UTC, kentoyamada100 commented on analyses/11_saitama/11_saitama_hr_2020_doc.md
> +* 郡の分割は、現行の区割りにて分割されている場合のみ許容
I changed this to `* 市区町村の複数選挙区への分割の制限(`add_constr_multisplits`)と全体の分割数の制限(`add_constr_total_splits`)をそれぞれを設定`
Please confirm that this is accurate

2022-07-05 07:21 UTC, kentoyamada100 commented on analyses/11_saitama/11_saitama_hr_2020_doc.md
> +
What you wrote here doesn't match with what you did in 01_prep. I gave up trying to guess what you actually did but I'm guessing that you should remove the description regarding 川口市藤倉 and that you should confirm whether 町字コード is 七左町 or 字道佛

2022-07-05 07:21 UTC, kentoyamada100 commented on analyses/11_saitama/03_visualization_11_saitama.R
> +
The 郡 boundary is not correct. Currently, you only have 北葛飾郡 in the data. This is what it looks like right now.
<img width="315" alt="Screen Shot 2022-07-05 at 16 16 19" src="https://user-images.githubusercontent.com/84626919/177271418-fcacfbc5-a9a3-4300-9d8e-3cdca1ed804a.png">

2022-07-05 10:38 UTC, shomiyazaki commented on analyses/11_saitama/11_saitama_hr_2020_doc.md
> +
Thanks. This was 川 **越** 市, not 川口, and this is what I forgot to remove after the new method.

2022-07-05 10:39 UTC, shomiyazaki commented on analyses/11_saitama/03_visualization_11_saitama.R
> +
Thanks! Solved!

2022-07-05 10:39 UTC, shomiyazaki commented on analyses/11_saitama/11_saitama_hr_2020_doc.md
> +* 郡の分割は、現行の区割りにて分割されている場合のみ許容
Thank you!

2022-07-05 10:46 UTC, merged