new sec
alarm-redist/japan pull request #48
Opened 2022-06-04 08:56 UTC by shomiyazaki

2022-06-05 07:59 UTC, kentoyamada100 commented on analyses/07_fukushima/07_fukushima_hr_2020_doc.html
> +<li>逐次モンテカルロ法(SMC)による2つの独立したシミュレーションにより、市区町村分割を許容しない案を20,000作成</li>
Isn't the number of simulations 2*15,000 ?

2022-06-05 07:59 UTC, kentoyamada100 requested changes

2022-06-05 07:59 UTC, kentoyamada100 commented on analyses/07_fukushima/07_fukushima_hr_2020_doc.md
> +* 逐次モンテカルロ法(SMC)による2つの独立したシミュレーションにより、市区町村分割を許容しない案を20,000作成
Isn't the number of simulations 2*15,000 ?

2022-06-05 15:41 UTC, shomiyazaki commented on analyses/07_fukushima/07_fukushima_hr_2020_doc.md
> +* 逐次モンテカルロ法(SMC)による2つの独立したシミュレーションにより、市区町村分割を許容しない案を20,000作成
@kentoyamada100 Thank you for pointing this out. I have pushed the updated version

2022-06-05 15:41 UTC, shomiyazaki commented
@kentoyamada100 Thank you for your reviews and comments. I have reflected on what you have pointed out!

2022-06-11 14:45 UTC, kentoyamada100 commented
@shomiyazaki I've merged this into main. If you haven't already, please upload the relevant data to dataverse

2022-06-11 14:46 UTC, merged