30 wakayama
alarm-redist/japan pull request #49
Opened 2022-06-04 10:57 UTC by shomiyazaki

New SMC

Hi @kentoyamada100 ! This is the PR for the updated template with the new SMC.

Although the output of `> summary(sim_smc_pref_0)` returns an error, it is inevitable because of the geographical nature of this shapefile and the small n_dist. Even when I increase `n_sim` up to 100k, it still `shows` the same error.

`> summary(sim_smc_pref_0)
SMC: 10,000 sampled plans of 2 districts on 15 units
`adapt_k_thresh`=0.985 • `seq_alpha`=0.5
`est_label_mult`=1 • `pop_temper`=0.05

Plan diversity 80% range: 0.0 to 0.4
✖ WARNING: Low plan diversity

Sampling diagnostics for SMC run 1 of 2
         Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1     4,907 (98.1%)     32.3%        0.28 3,171 (100%)      8 
Resample    4,653 (93.1%)       NA%        0.28 3,081 ( 97%)     NA 

Sampling diagnostics for SMC run 2 of 2
         Eff. samples (%) Acc. rate Log wgt. sd  Max. unique Est. k 
Split 1     4,908 (98.2%)     32.2%        0.27 3,152 (100%)      8 
Resample    4,657 (93.1%)       NA%        0.27 3,087 ( 98%)     NA 

•  Watch out for low effective samples, very low acceptance rates (less than 1%),
large std. devs. of the log weights (more than 3 or so), and low numbers of unique
plans. R-hat values for summary statistics should be between 1 and 1.05.
• Low diversity: Check for potential bottlenecks. Increase the number of samples.
Examine the diversity plot with `hist(plans_diversity(sim_smc_pref_0), breaks=24)`.
Consider weakening or removing constraints, or increasing the population tolerance.
If the accpetance rate drops quickly in the final splits, try increasing `pop_temper`
by 0.01.`

2022-06-05 08:03 UTC, kentoyamada100 commented
Did you try loosening the population tolerance? Also, what did the histogram look like originally and what does it look like now?

2022-06-05 15:37 UTC, shomiyazaki commented
@kentoyamada100 pop_tol is already very high (0.35) and the error won't disappear with 0.40.

Also, the histograms look like this.
![Screen Shot 2022-06-05 at 18 09 10](https://user-images.githubusercontent.com/70427938/172058445-05b37851-881e-44cf-9efb-e57b17528808.png)

2022-06-12 06:12 UTC, kentoyamada100 commented on analyses/30_wakayama/03_visualization_30_wakayama.R
>  ###############################################################################
`March 2022` -> `June 2022`

2022-06-12 06:15 UTC, kentoyamada100 requested changes
You don't need 30_wakayama_smc_10000_0.Rds, right? If so, pease delete i
<img width="522" alt="Screen Shot 2022-06-12 at 15 09 38" src="https://user-images.githubusercontent.com/84626919/173219489-0ae2f811-22bd-4b49-8397-be25076690a6.png">
t

2022-06-12 09:01 UTC, shomiyazaki commented
@kentoyamada100 Thank you for your review. I have delegated the irrelevant codes

2022-06-14 14:39 UTC, shomiyazaki commented
@kentoyamada100 Hi! Wakayama is ready with new `runs=4L`. I am looking forward to hearing your comments! Thank you!

2022-06-18 09:25 UTC, kentoyamada100 reviewed
Looks good. Please make sure to upload the new data to Dataverse. Also, please make a note somewhere that the plan diversity is low so that we can make sure to disclose that fact somewhere, when we make the results public

2022-06-19 03:34 UTC, shomiyazaki commented
- [ ] Dataverse
- [ ] Plan Diversity

2022-07-05 02:06 UTC, merged