34 hiroshima
alarm-redist/japan pull request #51
Opened 2022-06-05 09:41 UTC by kentoyamada100

2022-06-05 15:27 UTC, shomiyazaki requested changes
Hi @kentoyamada100 Thanks for your PR. Please refer to two comments below

2022-06-05 15:27 UTC, shomiyazaki commented on analyses/34_hiroshima/index.Rmd
> +* 逐次モンテカルロ法(SMC)による2つの独立したシミュレーションにより、市区町村分割を許容しない案、最大市区町村の分割を許容する案をそれぞれ100,000作成
`r format(nsims * 2, big.mark = ",")`

2022-06-05 15:27 UTC, shomiyazaki commented on analyses/34_hiroshima/index.Rmd
> +              nudge_x = c(0, 10000, 10000), # adjust the position of the labels
Would you switch 
dark blue and yellow
for a visual reason
![Screen Shot 2022-06-06 at 0 24 47](https://user-images.githubusercontent.com/70427938/172057943-19c91b6b-cfc8-4996-aa57-ca16f9124620.png)
?

2022-06-11 09:02 UTC, kentoyamada100 commented
@shomiyazaki ok, I've made those changes. Please merge this into main, if it's ok with you

2022-06-12 13:51 UTC, merged