38 ehime
alarm-redist/japan pull request #52
Opened 2022-06-05 22:47 UTC by kentoyamada100

2022-06-06 05:48 UTC, shomiyazaki requested changes

2022-06-06 05:48 UTC, shomiyazaki commented on analyses/38_ehime/01_prep_38_ehime.R
> +pop_tol <- 0.50 # Set so that re-sampling efficiencies are > 80% at each stage
I think this is too high (max_min = 3?). L et's discuss about `WARNING` in the meeting tonight

2022-06-06 10:18 UTC, kentoyamada100 commented on analyses/38_ehime/01_prep_38_ehime.R
> +pop_tol <- 0.50 # Set so that re-sampling efficiencies are > 80% at each stage
@shomiyazaki I think we agreed that we need to try out different constraints and set the constraint so that we get a diverse set of plans. By loosening the constraints and increasing the number of simulations, I maximized the plan diversity (even though I still have a warning message, the constraints I set maximizes the plan diversity). It turns out pop_tol = 0.25 yields a small number of unique plans

2022-06-11 14:26 UTC, kentoyamada100 commented
@shomiyazaki I've lowered the population tolerance to the original level. Unless you have any other comments, I think the analysis for Ehime is complete

2022-06-12 07:19 UTC, merged