25 shiga
alarm-redist/japan pull request #54
Opened 2022-06-07 11:41 UTC by shomiyazaki

New SMC.

Hi @kentoyamada100 The SMC run with the method that Shiro suggested in Slack. It would be appreciated if you start reviewing them. I am looking forward to your feedback and comments!

2022-06-12 06:35 UTC, kentoyamada100 requested changes

2022-06-12 06:35 UTC, kentoyamada100 commented on analyses/25_shiga/02_sim_25_shiga.R
> +  set.seed(2020)
<img width="743" alt="Screen Shot 2022-06-12 at 15 34 54" src="https://user-images.githubusercontent.com/84626919/173220547-533cbd91-1423-40b8-9bb0-612f96eeeff4.png">
<img width="752" alt="Screen Shot 2022-06-12 at 15 35 07" src="https://user-images.githubusercontent.com/84626919/173220560-ba47e1c5-a203-4dbe-8e7f-7dfa353dfd94.png">
Is this the latest version of the code? I still get this error... Were you able to resolve this issue?

2022-06-14 14:38 UTC, shomiyazaki commented
@kentoyamada100 Hi! Shiga is ready with new `runs=4L`. Thank you in advance, and I am looking forward to your reviews and comments

2022-06-18 09:53 UTC, kentoyamada100 requested changes
Please make the suggested changes and please also make sure to upload the new data to Dataverse, if you haven't already

2022-06-18 09:53 UTC, kentoyamada100 commented on analyses/25_shiga/02_sim_25_shiga.R
>                                  "_",
Please delete the old data.
<img width="409" alt="Screen Shot 2022-06-18 at 18 33 30" src="https://user-images.githubusercontent.com/84626919/174431804-716226a4-c4dd-416b-be4f-7daff3670f5d.png">

2022-06-18 09:53 UTC, kentoyamada100 commented on analyses/25_shiga/25_shiga_hr_2020_doc.md
> +`02_sim_25_shiga.R`にてシュミレーション（`redist_smc()`）を執行する際に、乱数のシードをランダムに設定した。これは、4つの独立したSMC (`runs = 4L`) を執行する際にランダムに発生するプログラムのエラーに対応するためである。なお、1つ (`1L`)と2つ(`2L`)の独立したSMCによって発生する結果や分布と比較することで、チェリーピッキングを回避し
You should put this in the section above this one ("設定"). "設定" is where we talk about the method we used. "データの処理" is where we explain the pre-processing steps (which we mainly do in 01.R)

2022-07-05 01:46 UTC, merged