01 hokkaido
alarm-redist/japan pull request #77
Opened 2022-07-05 19:20 UTC by shomiyazaki

2022-07-05 23:59 UTC, kentoyamada100 requested changes
@shomiyazaki I'm especially concerned about the constraints. You might need to re-run the simulations if you did not add the constraints (please refer to my comments)

2022-07-05 23:59 UTC, kentoyamada100 commented on analyses/01_hokkaido/01_hokkaido_hr_2020_doc.md
> +
You forgot to update this part. Also, I fixed the file names because the naming did not follow the convention. (ex: 1_hokkaido_ishikari_hr_2020_plans.rds -> 1_hokkaido_hr_2020_plans_ishikari.rds) Please double check before pushing the data to Dataverse

2022-07-05 23:59 UTC, kentoyamada100 commented on analyses/01_hokkaido/02_sim_01_hokkaido.R
> +  pop_temper = 0.05)
Did you add the constraints or not? If you didn't, you should re-run the simulations again, this time adding the constraints because I'm assuming that is what you intended to do

2022-07-05 23:59 UTC, kentoyamada100 commented on analyses/01_hokkaido/03_visualization_01_hokkaido.R
> +
I think this is what you meant but please correct this if this is not what you meant.

```
# 北しべりし定住自立圈, 上川中部定住自立圈, 西いぶり定住自立圈, 釧路定住自立圈,
# 北見地域定住自立圈, 十勝定住自立圈, 網走市大空町定住自立圈, 東胆振定住自立圈,
# 宗谷定住自立圈, 中空知定住自立圈, 北空知定住自立港, and 富良野地区定住自立圈
# are not split, because it is within the boundaries of the corresponding 振興局.
```

2022-07-05 23:59 UTC, kentoyamada100 commented on analyses/01_hokkaido/index.Rmd
> +
I could not understand where the district boundaries are. At first glance, it looks as if there are 7 districts. Maybe you should change the color of one of the blue or yellow districts.

2022-07-05 23:59 UTC, kentoyamada100 commented on analyses/01_hokkaido/01_hokkaido_hr_2020_doc.md
> +* 市区町村の分割数の制限 (`add_constr_splits`)と、市区町村の複数選挙区への分割の制限(`add_constr_multisplits`) をそれぞれを設定
Did you add impose constraints or not? It looks like you intended to impose those constraints only for 石狩, but you seem to have commented out that part so it seems that you did not add those constraints. Please refer to later comment

2022-07-06 09:20 UTC, shomiyazaki commented
Hi @kentoyamada100 ! Thanks for you reviews. I have reflected your comments, and rerun the simulations.
Since I need to stay at the campus more, I cannot knit the rmd. Would you knit Rmd and merge it into main? Thanks!

2022-07-06 13:42 UTC, merged