08 ibaraki
alarm-redist/japan pull request #79
Opened 2022-07-17 14:46 UTC by shomiyazaki

Hi @kentoyamada100 ! The analysis for Ibaraki is ready! It would be appreciated if you can start reviewing it when you have time! Thanks!

2022-07-23 07:29 UTC, kentoyamada100 requested changes
Sorry for the delay. Please see my comments and rerun the simulations. Also, could you re-request a review once you are done?

2022-07-23 07:29 UTC, kentoyamada100 commented on analyses/08_ibaraki/08_ibaraki_hr_2020_doc.md
> +* つくば市寺具を飛び地として扱わないため、シュミレーション前の`pref_map`作成時に飛地部分をシェイプファイルから除外した。
Again, you shouldn't have done this before the simulation

2022-07-23 07:29 UTC, kentoyamada100 commented on analyses/08_ibaraki/08_ibaraki_hr_2020_doc.md
> +
The file names are wrong

2022-07-23 07:29 UTC, kentoyamada100 commented on analyses/08_ibaraki/02_sim_08_ibaraki.R
> +  dplyr::filter(code==8220) %>%
The alternative would be to do something like this:
```
# Under the enacted plan, there are districts that are strictly speaking discontiguous
# because of the presence of small enclaves. We allow those small areas to be enclaved by
# another municipality in the simulated plans too.
allow_enclave <-
  c(27203, # 豊中市石橋麻田町
    27211, # 茨木市小坪井
    27215, # 寝屋川市打上元町
    27143, # 堺市東区丈六
    27222  # 羽曳野市埴生野
    )

# Define the codes of the municipalities that must not be split
respect_mun_code <- setdiff(unique(pref$code), c(mun_not_freeze, allow_enclave))

# Evaluate whether the municipalities that must be not be split are split in the simulated plans
respect_mun_matrix <- matrix(0, nrow = length(respect_mun_code), ncol = ncol(pref_smc_plans))
for(i in 1:length(respect_mun_code)){
  for(j in 1:ncol(pref_smc_plans)){
    respect_mun_matrix[i, j] <-
      length(pref_smc_plans[which(pref$code == respect_mun_code[i]),j]) -1 ==
      sum(duplicated(pref_smc_plans[which(pref$code == respect_mun_code[i]),j]))
  }
}

# Store results
results$respect_mun <- colSums(respect_mun_matrix) == length(respect_mun_code)
```
In any case, it is not justifiable to simply erase an area from `pref`

2022-07-23 07:29 UTC, kentoyamada100 commented on analyses/08_ibaraki/08_ibaraki_hr_2020_doc.md
> +
Maybe you should just list all the municipalities to show that you merged together 6 areas

2022-07-23 07:29 UTC, kentoyamada100 commented on analyses/08_ibaraki/index.Rmd
> +
You might want to make it clear that you merged together 6 areas

2022-07-25 04:32 UTC, shomiyazaki commented on analyses/08_ibaraki/02_sim_08_ibaraki.R
> +  dplyr::filter(code==8220) %>%
Thank you @kentoyamada100 . I will do this with `03_visualization`.
The reason why I could not use the method of Miyagi and Hiroshima is that つくば市 is adjacent to other municipalities that also have 飛地. Those 飛地 are respected under the status quo, so I cannot remove those area when we test the validity of plan.

2023-01-16 05:00 UTC, closed without merging