09 tochigi
alarm-redist/japan pull request #80
Opened 2022-07-17 16:13 UTC by shomiyazaki

@kentoyamada100 Hi! Tochigi is ready, too. It would be appreciated if you can review it when you have time! Thanks!

2022-07-23 09:13 UTC, kentoyamada100 requested changes

2022-07-23 09:13 UTC, kentoyamada100 commented on analyses/09_tochigi/09_tochigi_hr_2020_doc.md
> +<!---[When manual processing was necessary when assessing contiguity] 宮城野区港５丁目を飛び地として扱わないため、作成した区割り案に飛び地が生じているかどうか判断する際、一時的に宮城野区港５丁目及び隣接する七ヶ浜町をデータから除外した。-->
* 栃木県佐野市仙波町は厳密には飛び地とみなすこともできるが、現行の区割りでは飛び地として扱われていないため、本プロジェクトでも飛び地として扱わない。
-> 参考: 宮城野区港５丁目は飛び地として扱わない。そのため、アルゴリズムが作成した区割り案の飛び地の有無をテストする際に、宮城野区港５丁目と、隣接する七ヶ浜町を取り除いた。

* 宇都宮市（現行および平成の大合併前の旧宇都宮市）の人口は、県の1議席あたりの人口（県の総人口 / 選挙区数）より大きいため、区割りシミュレーションの対象外とし、宇都宮市・旧宇都宮市単独で選挙区を構成させた。
-> 参考: 最大市区町村の分割を許容しない区割りシミュレーションにおいて、倉敷市単独で選挙区を構成させるべく、倉敷市をポリゴンデータから取り除いた。

2022-07-23 09:13 UTC, kentoyamada100 commented on analyses/09_tochigi/09_tochigi_hr_2020_doc.md
> +
The file names are wrong

2022-07-24 04:46 UTC, shomiyazaki commented on analyses/09_tochigi/03_visualization_09_tochigi.R
> +
Thanks for pointing this out. 2nd and 3rd are the same, and I will add a comment

2022-07-24 04:51 UTC, shomiyazaki commented on analyses/09_tochigi/03_visualization_09_tochigi.R
> +  redist::redist.splits(pref_smc_plans_0, koiki_2_0)
Thanks. Yes, you're right

2022-07-24 05:00 UTC, shomiyazaki commented on analyses/09_tochigi/03_visualization_09_tochigi.R
> +
Thanks! Fixed!

2023-01-16 05:00 UTC, closed without merging